export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN'
export const SUCCESSFUL_LOGOUT = 'SUCCESSFUL_LOGOUT'